common: &common
  adapter: postgresql
  pool: 25

dev: &dev
  <<: *common
  username: postgres
  password: password

development:
  <<: *dev
  database: thought_stream_development

test:
  <<: *dev
  database: thought_stream_test